name: SwiftLint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: norio-nomura/action-swiftlint@v3
        with:
          args: --strict
