name: SwiftLint
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10"
      - name: Install SwiftLint
        run: |
          curl -sL https://raw.githubusercontent.com/realm/SwiftLint/master/Script/bootstrap | bash
          sudo mv swiftlint /usr/local/bin/
      - name: Run SwiftLint
        run: swiftlint lint --reporter github-actions-logging
