cd ~/Documents/Projects/Windsurf/mypropertyview/mypropertyview
mkdir -p .github/workflows
nano .github/workflows/swiftlint.yml
name: SwiftLint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install SwiftLint (Homebrew)
        run: |
          brew update
          brew install swiftlint
      - name: Run SwiftLint
        run: swiftlint --strict
